Python para análise de dados com Pandas - por Fernanda Santos

In [8]:
# Importando a biblioteca pandas
import pandas as pd

In [9]:
df = pd.read_csv("/content/drive/My Drive/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

# Nova seção

In [10]:
# Visualizando as 5 primeiras linhas da tabela
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [11]:
df.rename(columns={"country":"país", "continent":"continente", "year":"ano", "lifeExp": "expectativaDeVida", "pop": "populacao", "gdpPercap":"PIB"})

             país continente   ano  expectativaDeVida  populacao         PIB
0     Afghanistan       Asia  1952             28.801    8425333  779.445314
1     Afghanistan       Asia  1957             30.332    9240934  820.853030
2     Afghanistan       Asia  1962             31.997   10267083  853.100710
3     Afghanistan       Asia  1967             34.020   11537966  836.197138
4     Afghanistan       Asia  1972             36.088   13079460  739.981106
...           ...        ...   ...                ...        ...         ...
3307     Zimbabwe     Africa  1987             62.351    9216418  706.157306
3308     Zimbabwe     Africa  1992             60.377   10704340  693.420786
3309     Zimbabwe     Africa  1997             46.809   11404948  792.449960
3310     Zimbabwe     Africa  2002             39.989   11926563  672.038623
3311     Zimbabwe     Africa  2007             43.487   12311143  469.709298

[3312 rows x 6 columns]

In [12]:
# Atribuir as alterações à variável
df = df.rename(columns={"country":"país", "continent":"continente", "year":"ano", "lifeExp": "expectativaDeVida", "pop": "populacao", "gdpPercap":"PIB"})

In [13]:
# Mostras as 10 primeiras linhas
df.head(10)

          país continente   ano  expectativaDeVida  populacao         PIB
0  Afghanistan       Asia  1952             28.801    8425333  779.445314
1  Afghanistan       Asia  1957             30.332    9240934  820.853030
2  Afghanistan       Asia  1962             31.997   10267083  853.100710
3  Afghanistan       Asia  1967             34.020   11537966  836.197138
4  Afghanistan       Asia  1972             36.088   13079460  739.981106
5  Afghanistan       Asia  1977             38.438   14880372  786.113360
6  Afghanistan       Asia  1982             39.854   12881816  978.011439
7  Afghanistan       Asia  1987             40.822   13867957  852.395945
8  Afghanistan       Asia  1992             41.674   16317921  649.341395
9  Afghanistan       Asia  1997             41.763   22227415  635.341351

In [14]:
# Mostrar dimensão da tabela - total de linhas e colunas
df.shape

(3312, 6)

In [15]:
# Retorna o nome das colunas
df.columns

Index(['país', 'continente', 'ano', 'expectativaDeVida', 'populacao', 'PIB'], dtype='object')

In [16]:
# Retornar o tipo de dado de cada coluna
df.dtypes

país                  object
continente            object
ano                    int64
expectativaDeVida    float64
populacao              int64
PIB                  float64
dtype: object

In [17]:
# Retornar as últimas linhas da tabela
df.tail(15)

          país continente   ano  expectativaDeVida  populacao          PIB
3297    Zambia     Africa  1997             40.238    9417789  1071.353818
3298    Zambia     Africa  2002             39.193   10595811  1071.613938
3299    Zambia     Africa  2007             42.384   11746035  1271.211593
3300  Zimbabwe     Africa  1952             48.451    3080907   406.884115
3301  Zimbabwe     Africa  1957             50.469    3646340   518.764268
3302  Zimbabwe     Africa  1962             52.358    4277736   527.272182
3303  Zimbabwe     Africa  1967             53.995    4995432   569.795071
3304  Zimbabwe     Africa  1972             55.635    5861135   799.362176
3305  Zimbabwe     Africa  1977             57.674    6642107   685.587682
3306  Zimbabwe     Africa  1982             60.363    7636524   788.855041
3307  Zimbabwe     Africa  1987             62.351    9216418   706.157306
3308  Zimbabwe     Africa  1992             60.377   10704340   693.420786
3309  Zimbabwe     Africa  1997             46.809   11404948   792.449960
3310  Zimbabwe     Africa  2002             39.989   11926563   672.038623
3311  Zimbabwe     Africa  2007             43.487   12311143   469.709298

In [18]:
# Retorna infos estatisticas básicas do set
df.describe()

               ano  expectativaDeVida     populacao            PIB
count  3312.000000        3312.000000  3.312000e+03    3312.000000
mean   1980.301630          65.246871  3.161489e+07   11317.115805
std      16.927294          11.768412  1.041193e+08   11369.142739
min    1950.000000          23.599000  5.941200e+04     241.165877
25%    1967.000000          58.337500  2.678572e+06    2514.625266
50%    1982.000000          69.610000  7.557218e+06    7838.505123
75%    1996.000000          73.657750  1.958522e+07   17357.879170
max    2007.000000          82.670000  1.318683e+09  113523.132900

In [19]:
# Retornar os diferentes valores de uma coluna
df["continente"].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', nan, 'FSU', 'Oceania'],
      dtype=object)

In [20]:
# Usar o função loc para passar filtros no banco de dados
oceania = df.loc[df["continente"] == "Oceania"]
oceania.head()

     país continente   ano  expectativaDeVida  populacao          PIB
975  Fiji    Oceania  1962             56.494     421869  2039.393277
976  Fiji    Oceania  1967             58.607     485000  2170.073285
977  Fiji    Oceania  1972             60.642     544000  2797.759484
978  Fiji    Oceania  1977             62.669     599339  3182.569600
979  Fiji    Oceania  1982             64.683     658906  3209.257468

In [21]:
# Contando as quantidades de um valor
df.groupby("continente")["país"].nunique()

continente
Africa      51
Americas    25
Asia        41
Europe      35
FSU          6
Oceania      3
Name: país, dtype: int64

In [22]:
# Usando método groupby para fazer operações
df.groupby("ano")["expectativaDeVida"].mean()

ano
1950    62.002568
1951    65.904167
1952    49.206867
1953    66.674563
1954    67.459817
1955    67.806757
1956    67.950637
1957    51.614590
1958    68.815936
1959    68.226579
1960    68.470837
1961    68.862480
1962    54.035234
1963    69.595735
1964    70.063105
1965    70.259881
1966    70.447526
1967    56.263629
1968    70.689081
1969    70.653896
1970    70.961141
1971    71.103976
1972    58.474481
1973    71.500338
1974    71.778504
1975    71.939218
1976    72.158050
1977    60.429090
1978    72.717567
1979    73.018717
1980    73.064524
1981    73.337399
1982    62.365871
1983    73.787778
1984    74.100741
1985    74.112222
1986    74.452222
1987    63.984860
1988    74.760000
1989    74.924444
1990    74.283437
1991    74.374848
1992    65.008443
1993    74.324545
1994    74.456667
1995    74.552727
1996    75.029394
1997    65.873799
1998    75.569697
1999    75.703636
2000    76.026364
2001    76.257879
2002    66.835695
2003    76.586667
2004    76.921563
2005    76.718667
2006    77.887778
2007    67.868557
Name: expectativaDeVida, dtype: float64

In [23]:
df["PIB"].mean()

11317.115804696637

In [24]:
df["PIB"].sum()

37482287.5451553